# Docker-compose version
version: '2'

# Define the services/containers to be run
services:

  # Service name
  app: 
    # directory of Dockerfile
    build: ./ 
    ports:
      - "3000:3000"
    # link this service to database service
    links:
      - "database:db"
      - "vcenter:vcsa"
    volumes:
      - './:/app'


  # Database service name
  database:
    # image to build container from
    image: mongo 
    ports:
      - "27018:27017"

  # vcenter simulator
  vcenter:
    image: jakerobinson/vcsim
    #image: nimmis/vcsim
    ports:
      - "8989:8989"
      - "443:443"
    command: "./vcsim -httptest.serve 0.0.0.0:443 -trace -esx -app 10"
